<<<<<<< HEAD
# Generated by Django 3.2.6 on 2021-08-11 20:48

=======
# Generated by Django 3.2.6 on 2021-08-11 00:48

from django.conf import settings
>>>>>>> 1716ecabe0819ff25bce9c10fa67a99873d0a54f
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
<<<<<<< HEAD
=======
        ('posts', '0003_like'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
>>>>>>> 1716ecabe0819ff25bce9c10fa67a99873d0a54f
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
<<<<<<< HEAD
                ('text', models.TextField()),
                ('comment_created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-comment_created'],
            },
        ),
        migrations.CreateModel(
            name='LikeComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comments.comment')),
=======
                ('comment', models.TextField()),
                ('Post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_comment', to='posts.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_comment', to=settings.AUTH_USER_MODEL)),
>>>>>>> 1716ecabe0819ff25bce9c10fa67a99873d0a54f
            ],
        ),
    ]
