# Generated by Django 3.2.6 on 2021-08-11 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_likecomment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='likecomment',
            old_name='author',
            new_name='user',
        ),
    ]
