# Generated by Django 3.2.6 on 2021-08-11 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_countlike'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CountLike',
        ),
    ]
